import{a as P,S as R,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const $="https://pixabay.com/api/",B="50819756-11248eda55a36e78284ebe321",E=15,m=async(s,o=1)=>{const r={key:B,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:E};try{return(await P.get($,{params:r})).data}catch{throw new Error("Халепа! Щось пішло не так. Спробуй ще раз пізніше.")}},h=document.querySelector(".gallery"),y=document.querySelector(".loader"),M=new R(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".load-more-button"),f=s=>{const o=s.map(({webformatURL:r,largeImageURL:a,tags:e,likes:t,views:n,comments:S,downloads:q})=>`
    <li class="gallery-item">
    <a href="${a}">
    <img src="${r}" alt="${e}"/>
    </a>
    <div class="info">
    <p class="properties">Likes <span class="value">${t}</span></p>
    <p class="properties">Views <span class="value">${n}</span></p>
    <p class="properties">Comments <span class="value">${S}</span></p>
    <p class="properties">Downloads <span class="value">${q}</span></p>
    </div>

    </li>`).join("");h.insertAdjacentHTML("beforeend",o),M.refresh()},O=()=>{h.innerHTML=""},L=()=>{y.classList.remove("hidden")},v=()=>{y.classList.add("hidden")},w=()=>{g.classList.remove("hidden")},l=()=>{g.classList.add("hidden")},b=document.querySelector(".form"),u=b.elements["search-text"],x=document.querySelector(".load-more-button");let d="",c=1,p=0;b.addEventListener("submit",async s=>{s.preventDefault();const o=u.value.trim();if(!o){i.error({message:"Please enter a search term!",position:"topRight"});return}O(),l(),L(),d=o,c=1;try{const r=await m(d,c);if(p=r.totalHits,!r.hits.length){i.error({message:"Вибач! Немає зображень за твоїм запитом. Будь ласка, спробуй знову!",position:"topRight"});return}f(r.hits),p>r.hits.length&&w()}catch{i.error({message:"Oops! Something went wrong. Please try again later.",position:"topRight"})}finally{v(),u.value=""}});x.addEventListener("click",async()=>{c+=1,L(),l();try{const s=await m(d,c);f(s.hits);const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=p?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{v()}});
//# sourceMappingURL=index.js.map
